/**
 * Contract constants matching Move constants
 */
export const CONSTANTS = {
  // Room states
  STATE_CREATED: 0,
  STATE_OPEN: 1,
  STATE_CLOSED: 2,
  STATE_JURY_ACTIVE: 3,
  STATE_REVEAL_PHASE: 4,
  STATE_COMPLETE: 5,

  // Tier values
  TIER_A: 1,
  TIER_B: 2,
  TIER_INVALID: 0,

  // Limits
  MIN_JURORS: 3,
  MAX_JURORS: 25,
  MAX_ENTRIES_PER_ROOM: 50,
  MAX_ENCRYPTED_DATA_SIZE: 1024,
  MAX_CATEGORIES: 10,

  // Scoring
  MAX_CLIENT_SCORE: 100,
  MIN_SCORE: 0,
  MAX_SCORE: 100,

  // Module addresses
  MODULE_ADDRESS: '0x2bf0af3ddc84bf1d6d32e0961a678cca4cd49f4f3a79b5b9d3b892bbfa6cc455',
} as const;

/**
 * Error codes matching Move error constants
 */
export const ERRORS = {
  E_NOT_INITIALIZED: 101,
  E_ALREADY_INITIALIZED: 102,
  E_NOT_ADMIN: 103,
  E_INVALID_STATE: 104,
  E_ROOM_NOT_FOUND: 201,
  E_NOT_CLIENT: 202,
  E_NOT_OPEN: 203,
  E_ALREADY_HAS_KEYCARD: 204,
  E_NO_KEYCARD: 205,
  E_INVALID_ROOM_STATE: 206,
  E_NOT_JUROR: 301,
  E_ALREADY_VOTED: 302,
  E_NOT_IN_JURY_PHASE: 303,
  E_NOT_IN_REVEAL_PHASE: 304,
  E_ALREADY_COMMITTED: 305,
  E_ALREADY_REVEALED: 306,
  E_INVALID_REVEAL: 307,
  E_MAX_JURORS_REACHED: 308,
  E_MIN_JURORS_NOT_MET: 309,
  E_NOT_REGISTERED: 401,
  E_ALREADY_REGISTERED: 402,
  E_INVALID_CATEGORY: 403,
  E_NOT_PARTICIPANT: 501,
  E_SETTLEMENT_PENDING: 502,
  E_ALREADY_SETTLED: 503,
  E_INVALID_SCORE: 504,
  E_NOT_IN_COMMIT_PHASE: 601,
  E_INVALID_TIER: 602,
  E_DUPLICATE_ASSIGNMENT: 603,
  E_INVALID_TIER_COUNT: 604,
  E_ENCRYPTED_DATA_TOO_LARGE: 616,
} as const;

/**
 * Room state names for display
 */
export const STATES = {
  [CONSTANTS.STATE_CREATED]: 'Created',
  [CONSTANTS.STATE_OPEN]: 'Open',
  [CONSTANTS.STATE_CLOSED]: 'Closed',
  [CONSTANTS.STATE_JURY_ACTIVE]: 'Jury Active',
  [CONSTANTS.STATE_REVEAL_PHASE]: 'Reveal Phase',
  [CONSTANTS.STATE_COMPLETE]: 'Complete',
} as const;
